version: '3.0'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_HOST_IP: 107.20.25.120:80
    ports:
     "3306:3306"  

php:    
  image: php:8.1-apache
  ports:
    "9000:9000"
  volumes:
    ./www:/var/www/html
  depends_on:
    mysql

apache:
    image: httpd:latest
    ports:
      - "8080:80"
    volumes:
      - ./apache2.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php

volumes:
  mysql-data: