# Use the official Apache image
FROM httpd:latest

# Copy website files into the Apache web directory
COPY index.html /usr/local/apache2/htdocs/
COPY index.js /usr/local/apache2/htdocs/
COPY index.css /usr/local/apache2/htdocs/


# Expose HTTP port
EXPOSE 80


