version: '3.0'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_HOST_IP: 44.202.135.19.10
    ports:
     "3306:3306"  

php:    
  image: php:8.1-apache
  ports:
    "9000:9000"
  volumes:
    ./www:/var/www/html
  depends_on:
    mysql

nginx:
  image: nginx:latest
  ports:
    "80:80"
  volumes:
    ./nginx.conf:/etc/nginx/
    nginx.conf:ro
    ./www:/usr/share/nginx/html:ro
  depends_on:
    php   